apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-config
  namespace: taskmanager
data:
  POSTGRES_DB: taskdb
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  NODE_ENV: production
  PORT: "3000"